language: java
#jdk: openjdk14 #problems with sonar-maven-plugin
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]$/"
    - master
notifications:
  email:
    recipients:
      - alexcabezas0705@gmail.es

before_install:
  - chmod +x mvnw
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=alexcabezas2018 -Dsonar.login=$SONAR
deploy:
  provider: heroku
  api_key: $HEROKU
  on:
    branch: master